services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "5001:5000"
    networks:
      - airflow_default
    restart: unless-stopped

networks:
  airflow_default:
    external: true
